Sprint2
ClevertecFrontendLab/sprint2-KaPuTaH-UluTka pull request #1
Opened 2023-02-09 11:20 UTC by KaPuTaH-UluTka

2023-02-09 11:23 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675941795/slider%20one%20foto%20768px.png)

2023-02-09 11:46 UTC, klichkovskiy requested changes
Пересмотри свое приложение. Все очень плохо работает!

2023-02-09 11:46 UTC, klichkovskiy commented on src/index.tsx
> +root.render(
![image](https://user-images.githubusercontent.com/62481116/217804133-1389907b-a1e9-4871-aaa0-646e953ecc6a.png)
доделай

2023-02-09 11:46 UTC, klichkovskiy commented on src/index.tsx
> +root.render(
![image](https://user-images.githubusercontent.com/62481116/217804225-28860192-966f-475e-a8f0-8738782d1890.png)
доделай

2023-02-09 11:46 UTC, klichkovskiy commented on src/index.tsx
> +root.render(
![image](https://user-images.githubusercontent.com/62481116/217804295-ffc9e37b-ee4b-4e20-b47a-0f105aad067d.png)
доделай

2023-02-09 12:18 UTC, KaPuTaH-UluTka commented on src/index.tsx
> +root.render(
Добрый день! Как я понял все вопросы касаются именно "резиновости" верстки?

2023-02-09 17:51 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965109/slider%20one%20foto%20768px.png)

2023-02-09 17:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1675965299/slider%20one%20foto%20768px.png)

2023-02-10 08:29 UTC, klichkovskiy requested changes

2023-02-10 10:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 60%.
Общее количество тестов: 10.
Количество непройденных тестов: 4.
***
**Test width 320px -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/Test%20width%20320px%20--%20test%20layout%20burger-menu%20(failed).png)
***
**Test width 320px -- test search (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/Test%20width%20320px%20--%20test%20search%20(failed).png)
***
**Test width 320px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/Test%20width%20320px%20--%20test%20slider%20(failed).png)
***
**Test width 768px -- test slider (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/Test%20width%20768px%20--%20test%20slider%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/app%20768px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/slider%20after%201440px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/slider%20before%201440px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/slider%20more%20two%20foto%201440px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/slider%20not%20foto%201440px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023203/slider%20one%20foto%201440px.png)

2023-02-10 10:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1676023689/slider%20one%20foto%20768px.png)

2023-02-10 10:16 UTC, klichkovskiy approved these changes
Удачи на 3 спринте!

2023-02-10 10:18 UTC, merged